//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clienteP2.procesoCompra {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/proveedor3/", ConfigurationName="procesoCompra.proveedor3")]
    public interface proveedor3 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor3/SolicitarPresupuesto", ReplyAction="*")]
        clienteP2.procesoCompra.SolicitarPresupuestoResponse SolicitarPresupuesto(clienteP2.procesoCompra.SolicitarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor3/SolicitarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse> SolicitarPresupuestoAsync(clienteP2.procesoCompra.SolicitarPresupuestoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor3/OrdenarCompra", ReplyAction="*")]
        clienteP2.procesoCompra.OrdenarCompraResponse OrdenarCompra(clienteP2.procesoCompra.OrdenarCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor3/OrdenarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse> OrdenarCompraAsync(clienteP2.procesoCompra.OrdenarCompraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor3/ActualizarStock", ReplyAction="*")]
        clienteP2.procesoCompra.ActualizarStockResponse ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor3/ActualizarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse> ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarPresupuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarPresupuesto", Namespace="http://www.example.org/proveedor3/", Order=0)]
        public clienteP2.procesoCompra.SolicitarPresupuestoRequestBody Body;
        
        public SolicitarPresupuestoRequest() {
        }
        
        public SolicitarPresupuestoRequest(clienteP2.procesoCompra.SolicitarPresupuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SolicitarPresupuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public SolicitarPresupuestoRequestBody() {
        }
        
        public SolicitarPresupuestoRequestBody(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarPresupuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarPresupuestoResponse", Namespace="http://www.example.org/proveedor3/", Order=0)]
        public clienteP2.procesoCompra.SolicitarPresupuestoResponseBody Body;
        
        public SolicitarPresupuestoResponse() {
        }
        
        public SolicitarPresupuestoResponse(clienteP2.procesoCompra.SolicitarPresupuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SolicitarPresupuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precio;
        
        public SolicitarPresupuestoResponseBody() {
        }
        
        public SolicitarPresupuestoResponseBody(float precio) {
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenarCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenarCompra", Namespace="http://www.example.org/proveedor3/", Order=0)]
        public clienteP2.procesoCompra.OrdenarCompraRequestBody Body;
        
        public OrdenarCompraRequest() {
        }
        
        public OrdenarCompraRequest(clienteP2.procesoCompra.OrdenarCompraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrdenarCompraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public OrdenarCompraRequestBody() {
        }
        
        public OrdenarCompraRequestBody(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenarCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenarCompraResponse", Namespace="http://www.example.org/proveedor3/", Order=0)]
        public clienteP2.procesoCompra.OrdenarCompraResponseBody Body;
        
        public OrdenarCompraResponse() {
        }
        
        public OrdenarCompraResponse(clienteP2.procesoCompra.OrdenarCompraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrdenarCompraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public OrdenarCompraResponseBody() {
        }
        
        public OrdenarCompraResponseBody(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStock", Namespace="http://www.example.org/proveedor3/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockRequestBody Body;
        
        public ActualizarStockRequest() {
        }
        
        public ActualizarStockRequest(clienteP2.procesoCompra.ActualizarStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public ActualizarStockRequestBody() {
        }
        
        public ActualizarStockRequestBody(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStockResponse", Namespace="http://www.example.org/proveedor3/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockResponseBody Body;
        
        public ActualizarStockResponse() {
        }
        
        public ActualizarStockResponse(clienteP2.procesoCompra.ActualizarStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public ActualizarStockResponseBody() {
        }
        
        public ActualizarStockResponseBody(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface proveedor3Channel : clienteP2.procesoCompra.proveedor3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class proveedor3Client : System.ServiceModel.ClientBase<clienteP2.procesoCompra.proveedor3>, clienteP2.procesoCompra.proveedor3 {
        
        public proveedor3Client() {
        }
        
        public proveedor3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public proveedor3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proveedor3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proveedor3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.SolicitarPresupuestoResponse clienteP2.procesoCompra.proveedor3.SolicitarPresupuesto(clienteP2.procesoCompra.SolicitarPresupuestoRequest request) {
            return base.Channel.SolicitarPresupuesto(request);
        }
        
        public float SolicitarPresupuesto(int nUnidades, string refProd) {
            clienteP2.procesoCompra.SolicitarPresupuestoRequest inValue = new clienteP2.procesoCompra.SolicitarPresupuestoRequest();
            inValue.Body = new clienteP2.procesoCompra.SolicitarPresupuestoRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.SolicitarPresupuestoResponse retVal = ((clienteP2.procesoCompra.proveedor3)(this)).SolicitarPresupuesto(inValue);
            return retVal.Body.precio;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse> clienteP2.procesoCompra.proveedor3.SolicitarPresupuestoAsync(clienteP2.procesoCompra.SolicitarPresupuestoRequest request) {
            return base.Channel.SolicitarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse> SolicitarPresupuestoAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.SolicitarPresupuestoRequest inValue = new clienteP2.procesoCompra.SolicitarPresupuestoRequest();
            inValue.Body = new clienteP2.procesoCompra.SolicitarPresupuestoRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor3)(this)).SolicitarPresupuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.OrdenarCompraResponse clienteP2.procesoCompra.proveedor3.OrdenarCompra(clienteP2.procesoCompra.OrdenarCompraRequest request) {
            return base.Channel.OrdenarCompra(request);
        }
        
        public bool OrdenarCompra(int nUnidades, string refProd) {
            clienteP2.procesoCompra.OrdenarCompraRequest inValue = new clienteP2.procesoCompra.OrdenarCompraRequest();
            inValue.Body = new clienteP2.procesoCompra.OrdenarCompraRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.OrdenarCompraResponse retVal = ((clienteP2.procesoCompra.proveedor3)(this)).OrdenarCompra(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse> clienteP2.procesoCompra.proveedor3.OrdenarCompraAsync(clienteP2.procesoCompra.OrdenarCompraRequest request) {
            return base.Channel.OrdenarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse> OrdenarCompraAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.OrdenarCompraRequest inValue = new clienteP2.procesoCompra.OrdenarCompraRequest();
            inValue.Body = new clienteP2.procesoCompra.OrdenarCompraRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor3)(this)).OrdenarCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.ActualizarStockResponse clienteP2.procesoCompra.proveedor3.ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest request) {
            return base.Channel.ActualizarStock(request);
        }
        
        public bool ActualizarStock(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest inValue = new clienteP2.procesoCompra.ActualizarStockRequest();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.ActualizarStockResponse retVal = ((clienteP2.procesoCompra.proveedor3)(this)).ActualizarStock(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse> clienteP2.procesoCompra.proveedor3.ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest request) {
            return base.Channel.ActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse> ActualizarStockAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest inValue = new clienteP2.procesoCompra.ActualizarStockRequest();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor3)(this)).ActualizarStockAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://procesoCompra.bpel.mtis", ConfigurationName="procesoCompra.procesoCompra")]
    public interface procesoCompra {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación process no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://procesoCompra.bpel.mtis/process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        clienteP2.procesoCompra.processResponse process(clienteP2.procesoCompra.processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://procesoCompra.bpel.mtis/process", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.processResponse> processAsync(clienteP2.procesoCompra.processRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://procesoCompra.bpel.mtis")]
    public partial class procesoCompraRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string refProductoField;
        
        private int cantidadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string refProducto {
            get {
                return this.refProductoField;
            }
            set {
                this.refProductoField = value;
                this.RaisePropertyChanged("refProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://procesoCompra.bpel.mtis")]
    public partial class procesoCompraResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool pedidoEfectuadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool pedidoEfectuado {
            get {
                return this.pedidoEfectuadoField;
            }
            set {
                this.pedidoEfectuadoField = value;
                this.RaisePropertyChanged("pedidoEfectuado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://procesoCompra.bpel.mtis", Order=0)]
        public clienteP2.procesoCompra.procesoCompraRequest procesoCompraRequest;
        
        public processRequest() {
        }
        
        public processRequest(clienteP2.procesoCompra.procesoCompraRequest procesoCompraRequest) {
            this.procesoCompraRequest = procesoCompraRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://procesoCompra.bpel.mtis", Order=0)]
        public clienteP2.procesoCompra.procesoCompraResponse procesoCompraResponse;
        
        public processResponse() {
        }
        
        public processResponse(clienteP2.procesoCompra.procesoCompraResponse procesoCompraResponse) {
            this.procesoCompraResponse = procesoCompraResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface procesoCompraChannel : clienteP2.procesoCompra.procesoCompra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class procesoCompraClient : System.ServiceModel.ClientBase<clienteP2.procesoCompra.procesoCompra>, clienteP2.procesoCompra.procesoCompra {
        
        public procesoCompraClient() {
        }
        
        public procesoCompraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public procesoCompraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public procesoCompraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public procesoCompraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.processResponse clienteP2.procesoCompra.procesoCompra.process(clienteP2.procesoCompra.processRequest request) {
            return base.Channel.process(request);
        }
        
        public clienteP2.procesoCompra.procesoCompraResponse process(clienteP2.procesoCompra.procesoCompraRequest procesoCompraRequest) {
            clienteP2.procesoCompra.processRequest inValue = new clienteP2.procesoCompra.processRequest();
            inValue.procesoCompraRequest = procesoCompraRequest;
            clienteP2.procesoCompra.processResponse retVal = ((clienteP2.procesoCompra.procesoCompra)(this)).process(inValue);
            return retVal.procesoCompraResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.processResponse> clienteP2.procesoCompra.procesoCompra.processAsync(clienteP2.procesoCompra.processRequest request) {
            return base.Channel.processAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.processResponse> processAsync(clienteP2.procesoCompra.procesoCompraRequest procesoCompraRequest) {
            clienteP2.procesoCompra.processRequest inValue = new clienteP2.procesoCompra.processRequest();
            inValue.procesoCompraRequest = procesoCompraRequest;
            return ((clienteP2.procesoCompra.procesoCompra)(this)).processAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/gestionAlmacen/", ConfigurationName="procesoCompra.gestionAlmacen")]
    public interface gestionAlmacen {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/gestionAlmacen/ComprobarStock", ReplyAction="*")]
        clienteP2.procesoCompra.ComprobarStockResponse ComprobarStock(clienteP2.procesoCompra.ComprobarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/gestionAlmacen/ComprobarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ComprobarStockResponse> ComprobarStockAsync(clienteP2.procesoCompra.ComprobarStockRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/gestionAlmacen/ActualizarStock", ReplyAction="*")]
        clienteP2.procesoCompra.ActualizarStockResponse1 ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/gestionAlmacen/ActualizarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse1> ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobarStock", Namespace="http://www.example.org/gestionAlmacen/", Order=0)]
        public clienteP2.procesoCompra.ComprobarStockRequestBody Body;
        
        public ComprobarStockRequest() {
        }
        
        public ComprobarStockRequest(clienteP2.procesoCompra.ComprobarStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ComprobarStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public ComprobarStockRequestBody() {
        }
        
        public ComprobarStockRequestBody(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobarStockResponse", Namespace="http://www.example.org/gestionAlmacen/", Order=0)]
        public clienteP2.procesoCompra.ComprobarStockResponseBody Body;
        
        public ComprobarStockResponse() {
        }
        
        public ComprobarStockResponse(clienteP2.procesoCompra.ComprobarStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ComprobarStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool existe;
        
        public ComprobarStockResponseBody() {
        }
        
        public ComprobarStockResponseBody(bool existe) {
            this.existe = existe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStock", Namespace="http://www.example.org/gestionAlmacen/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockRequest1Body Body;
        
        public ActualizarStockRequest1() {
        }
        
        public ActualizarStockRequest1(clienteP2.procesoCompra.ActualizarStockRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public ActualizarStockRequest1Body() {
        }
        
        public ActualizarStockRequest1Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStockResponse", Namespace="http://www.example.org/gestionAlmacen/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockResponse1Body Body;
        
        public ActualizarStockResponse1() {
        }
        
        public ActualizarStockResponse1(clienteP2.procesoCompra.ActualizarStockResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public ActualizarStockResponse1Body() {
        }
        
        public ActualizarStockResponse1Body(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gestionAlmacenChannel : clienteP2.procesoCompra.gestionAlmacen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gestionAlmacenClient : System.ServiceModel.ClientBase<clienteP2.procesoCompra.gestionAlmacen>, clienteP2.procesoCompra.gestionAlmacen {
        
        public gestionAlmacenClient() {
        }
        
        public gestionAlmacenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public gestionAlmacenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gestionAlmacenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gestionAlmacenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.ComprobarStockResponse clienteP2.procesoCompra.gestionAlmacen.ComprobarStock(clienteP2.procesoCompra.ComprobarStockRequest request) {
            return base.Channel.ComprobarStock(request);
        }
        
        public bool ComprobarStock(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ComprobarStockRequest inValue = new clienteP2.procesoCompra.ComprobarStockRequest();
            inValue.Body = new clienteP2.procesoCompra.ComprobarStockRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.ComprobarStockResponse retVal = ((clienteP2.procesoCompra.gestionAlmacen)(this)).ComprobarStock(inValue);
            return retVal.Body.existe;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ComprobarStockResponse> clienteP2.procesoCompra.gestionAlmacen.ComprobarStockAsync(clienteP2.procesoCompra.ComprobarStockRequest request) {
            return base.Channel.ComprobarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.ComprobarStockResponse> ComprobarStockAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ComprobarStockRequest inValue = new clienteP2.procesoCompra.ComprobarStockRequest();
            inValue.Body = new clienteP2.procesoCompra.ComprobarStockRequestBody();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.gestionAlmacen)(this)).ComprobarStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.ActualizarStockResponse1 clienteP2.procesoCompra.gestionAlmacen.ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest1 request) {
            return base.Channel.ActualizarStock(request);
        }
        
        public bool ActualizarStock(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest1 inValue = new clienteP2.procesoCompra.ActualizarStockRequest1();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequest1Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.ActualizarStockResponse1 retVal = ((clienteP2.procesoCompra.gestionAlmacen)(this)).ActualizarStock(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse1> clienteP2.procesoCompra.gestionAlmacen.ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest1 request) {
            return base.Channel.ActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse1> ActualizarStockAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest1 inValue = new clienteP2.procesoCompra.ActualizarStockRequest1();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequest1Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.gestionAlmacen)(this)).ActualizarStockAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/proveedor1/", ConfigurationName="procesoCompra.proveedor1")]
    public interface proveedor1 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor1/SolicitarPresupuesto", ReplyAction="*")]
        clienteP2.procesoCompra.SolicitarPresupuestoResponse1 SolicitarPresupuesto(clienteP2.procesoCompra.SolicitarPresupuestoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor1/SolicitarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse1> SolicitarPresupuestoAsync(clienteP2.procesoCompra.SolicitarPresupuestoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor1/OrdenarCompra", ReplyAction="*")]
        clienteP2.procesoCompra.OrdenarCompraResponse1 OrdenarCompra(clienteP2.procesoCompra.OrdenarCompraRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor1/OrdenarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse1> OrdenarCompraAsync(clienteP2.procesoCompra.OrdenarCompraRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor1/ActualizarStock", ReplyAction="*")]
        clienteP2.procesoCompra.ActualizarStockResponse2 ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor1/ActualizarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse2> ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest2 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarPresupuestoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarPresupuesto", Namespace="http://www.example.org/proveedor1/", Order=0)]
        public clienteP2.procesoCompra.SolicitarPresupuestoRequest1Body Body;
        
        public SolicitarPresupuestoRequest1() {
        }
        
        public SolicitarPresupuestoRequest1(clienteP2.procesoCompra.SolicitarPresupuestoRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SolicitarPresupuestoRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public SolicitarPresupuestoRequest1Body() {
        }
        
        public SolicitarPresupuestoRequest1Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarPresupuestoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarPresupuestoResponse", Namespace="http://www.example.org/proveedor1/", Order=0)]
        public clienteP2.procesoCompra.SolicitarPresupuestoResponse1Body Body;
        
        public SolicitarPresupuestoResponse1() {
        }
        
        public SolicitarPresupuestoResponse1(clienteP2.procesoCompra.SolicitarPresupuestoResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SolicitarPresupuestoResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float valor;
        
        public SolicitarPresupuestoResponse1Body() {
        }
        
        public SolicitarPresupuestoResponse1Body(float valor) {
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenarCompraRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenarCompra", Namespace="http://www.example.org/proveedor1/", Order=0)]
        public clienteP2.procesoCompra.OrdenarCompraRequest1Body Body;
        
        public OrdenarCompraRequest1() {
        }
        
        public OrdenarCompraRequest1(clienteP2.procesoCompra.OrdenarCompraRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrdenarCompraRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public OrdenarCompraRequest1Body() {
        }
        
        public OrdenarCompraRequest1Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenarCompraResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenarCompraResponse", Namespace="http://www.example.org/proveedor1/", Order=0)]
        public clienteP2.procesoCompra.OrdenarCompraResponse1Body Body;
        
        public OrdenarCompraResponse1() {
        }
        
        public OrdenarCompraResponse1(clienteP2.procesoCompra.OrdenarCompraResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrdenarCompraResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public OrdenarCompraResponse1Body() {
        }
        
        public OrdenarCompraResponse1Body(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockRequest2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStock", Namespace="http://www.example.org/proveedor1/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockRequest2Body Body;
        
        public ActualizarStockRequest2() {
        }
        
        public ActualizarStockRequest2(clienteP2.procesoCompra.ActualizarStockRequest2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockRequest2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public ActualizarStockRequest2Body() {
        }
        
        public ActualizarStockRequest2Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStockResponse", Namespace="http://www.example.org/proveedor1/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockResponse2Body Body;
        
        public ActualizarStockResponse2() {
        }
        
        public ActualizarStockResponse2(clienteP2.procesoCompra.ActualizarStockResponse2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockResponse2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public ActualizarStockResponse2Body() {
        }
        
        public ActualizarStockResponse2Body(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface proveedor1Channel : clienteP2.procesoCompra.proveedor1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class proveedor1Client : System.ServiceModel.ClientBase<clienteP2.procesoCompra.proveedor1>, clienteP2.procesoCompra.proveedor1 {
        
        public proveedor1Client() {
        }
        
        public proveedor1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public proveedor1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proveedor1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proveedor1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.SolicitarPresupuestoResponse1 clienteP2.procesoCompra.proveedor1.SolicitarPresupuesto(clienteP2.procesoCompra.SolicitarPresupuestoRequest1 request) {
            return base.Channel.SolicitarPresupuesto(request);
        }
        
        public float SolicitarPresupuesto(int nUnidades, string refProd) {
            clienteP2.procesoCompra.SolicitarPresupuestoRequest1 inValue = new clienteP2.procesoCompra.SolicitarPresupuestoRequest1();
            inValue.Body = new clienteP2.procesoCompra.SolicitarPresupuestoRequest1Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.SolicitarPresupuestoResponse1 retVal = ((clienteP2.procesoCompra.proveedor1)(this)).SolicitarPresupuesto(inValue);
            return retVal.Body.valor;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse1> clienteP2.procesoCompra.proveedor1.SolicitarPresupuestoAsync(clienteP2.procesoCompra.SolicitarPresupuestoRequest1 request) {
            return base.Channel.SolicitarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse1> SolicitarPresupuestoAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.SolicitarPresupuestoRequest1 inValue = new clienteP2.procesoCompra.SolicitarPresupuestoRequest1();
            inValue.Body = new clienteP2.procesoCompra.SolicitarPresupuestoRequest1Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor1)(this)).SolicitarPresupuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.OrdenarCompraResponse1 clienteP2.procesoCompra.proveedor1.OrdenarCompra(clienteP2.procesoCompra.OrdenarCompraRequest1 request) {
            return base.Channel.OrdenarCompra(request);
        }
        
        public bool OrdenarCompra(int nUnidades, string refProd) {
            clienteP2.procesoCompra.OrdenarCompraRequest1 inValue = new clienteP2.procesoCompra.OrdenarCompraRequest1();
            inValue.Body = new clienteP2.procesoCompra.OrdenarCompraRequest1Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.OrdenarCompraResponse1 retVal = ((clienteP2.procesoCompra.proveedor1)(this)).OrdenarCompra(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse1> clienteP2.procesoCompra.proveedor1.OrdenarCompraAsync(clienteP2.procesoCompra.OrdenarCompraRequest1 request) {
            return base.Channel.OrdenarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse1> OrdenarCompraAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.OrdenarCompraRequest1 inValue = new clienteP2.procesoCompra.OrdenarCompraRequest1();
            inValue.Body = new clienteP2.procesoCompra.OrdenarCompraRequest1Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor1)(this)).OrdenarCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.ActualizarStockResponse2 clienteP2.procesoCompra.proveedor1.ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest2 request) {
            return base.Channel.ActualizarStock(request);
        }
        
        public bool ActualizarStock(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest2 inValue = new clienteP2.procesoCompra.ActualizarStockRequest2();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequest2Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.ActualizarStockResponse2 retVal = ((clienteP2.procesoCompra.proveedor1)(this)).ActualizarStock(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse2> clienteP2.procesoCompra.proveedor1.ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest2 request) {
            return base.Channel.ActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse2> ActualizarStockAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest2 inValue = new clienteP2.procesoCompra.ActualizarStockRequest2();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequest2Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor1)(this)).ActualizarStockAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/proveedor2/", ConfigurationName="procesoCompra.proveedor2")]
    public interface proveedor2 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor2/SolicitarPresupuesto", ReplyAction="*")]
        clienteP2.procesoCompra.SolicitarPresupuestoResponse2 SolicitarPresupuesto(clienteP2.procesoCompra.SolicitarPresupuestoRequest2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor2/SolicitarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse2> SolicitarPresupuestoAsync(clienteP2.procesoCompra.SolicitarPresupuestoRequest2 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor2/OrdenarCompra", ReplyAction="*")]
        clienteP2.procesoCompra.OrdenarCompraResponse2 OrdenarCompra(clienteP2.procesoCompra.OrdenarCompraRequest2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor2/OrdenarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse2> OrdenarCompraAsync(clienteP2.procesoCompra.OrdenarCompraRequest2 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento refProd del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor2/ActualizarStock", ReplyAction="*")]
        clienteP2.procesoCompra.ActualizarStockResponse3 ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/proveedor2/ActualizarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse3> ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest3 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarPresupuestoRequest2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarPresupuesto", Namespace="http://www.example.org/proveedor2/", Order=0)]
        public clienteP2.procesoCompra.SolicitarPresupuestoRequest2Body Body;
        
        public SolicitarPresupuestoRequest2() {
        }
        
        public SolicitarPresupuestoRequest2(clienteP2.procesoCompra.SolicitarPresupuestoRequest2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SolicitarPresupuestoRequest2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public SolicitarPresupuestoRequest2Body() {
        }
        
        public SolicitarPresupuestoRequest2Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarPresupuestoResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarPresupuestoResponse", Namespace="http://www.example.org/proveedor2/", Order=0)]
        public clienteP2.procesoCompra.SolicitarPresupuestoResponse2Body Body;
        
        public SolicitarPresupuestoResponse2() {
        }
        
        public SolicitarPresupuestoResponse2(clienteP2.procesoCompra.SolicitarPresupuestoResponse2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SolicitarPresupuestoResponse2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precio;
        
        public SolicitarPresupuestoResponse2Body() {
        }
        
        public SolicitarPresupuestoResponse2Body(float precio) {
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenarCompraRequest2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenarCompra", Namespace="http://www.example.org/proveedor2/", Order=0)]
        public clienteP2.procesoCompra.OrdenarCompraRequest2Body Body;
        
        public OrdenarCompraRequest2() {
        }
        
        public OrdenarCompraRequest2(clienteP2.procesoCompra.OrdenarCompraRequest2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrdenarCompraRequest2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public OrdenarCompraRequest2Body() {
        }
        
        public OrdenarCompraRequest2Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenarCompraResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenarCompraResponse", Namespace="http://www.example.org/proveedor2/", Order=0)]
        public clienteP2.procesoCompra.OrdenarCompraResponse2Body Body;
        
        public OrdenarCompraResponse2() {
        }
        
        public OrdenarCompraResponse2(clienteP2.procesoCompra.OrdenarCompraResponse2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrdenarCompraResponse2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public OrdenarCompraResponse2Body() {
        }
        
        public OrdenarCompraResponse2Body(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockRequest3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStock", Namespace="http://www.example.org/proveedor2/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockRequest3Body Body;
        
        public ActualizarStockRequest3() {
        }
        
        public ActualizarStockRequest3(clienteP2.procesoCompra.ActualizarStockRequest3Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockRequest3Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nUnidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string refProd;
        
        public ActualizarStockRequest3Body() {
        }
        
        public ActualizarStockRequest3Body(int nUnidades, string refProd) {
            this.nUnidades = nUnidades;
            this.refProd = refProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarStockResponse3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarStockResponse", Namespace="http://www.example.org/proveedor2/", Order=0)]
        public clienteP2.procesoCompra.ActualizarStockResponse3Body Body;
        
        public ActualizarStockResponse3() {
        }
        
        public ActualizarStockResponse3(clienteP2.procesoCompra.ActualizarStockResponse3Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarStockResponse3Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public ActualizarStockResponse3Body() {
        }
        
        public ActualizarStockResponse3Body(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface proveedor2Channel : clienteP2.procesoCompra.proveedor2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class proveedor2Client : System.ServiceModel.ClientBase<clienteP2.procesoCompra.proveedor2>, clienteP2.procesoCompra.proveedor2 {
        
        public proveedor2Client() {
        }
        
        public proveedor2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public proveedor2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proveedor2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proveedor2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.SolicitarPresupuestoResponse2 clienteP2.procesoCompra.proveedor2.SolicitarPresupuesto(clienteP2.procesoCompra.SolicitarPresupuestoRequest2 request) {
            return base.Channel.SolicitarPresupuesto(request);
        }
        
        public float SolicitarPresupuesto(int nUnidades, string refProd) {
            clienteP2.procesoCompra.SolicitarPresupuestoRequest2 inValue = new clienteP2.procesoCompra.SolicitarPresupuestoRequest2();
            inValue.Body = new clienteP2.procesoCompra.SolicitarPresupuestoRequest2Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.SolicitarPresupuestoResponse2 retVal = ((clienteP2.procesoCompra.proveedor2)(this)).SolicitarPresupuesto(inValue);
            return retVal.Body.precio;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse2> clienteP2.procesoCompra.proveedor2.SolicitarPresupuestoAsync(clienteP2.procesoCompra.SolicitarPresupuestoRequest2 request) {
            return base.Channel.SolicitarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.SolicitarPresupuestoResponse2> SolicitarPresupuestoAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.SolicitarPresupuestoRequest2 inValue = new clienteP2.procesoCompra.SolicitarPresupuestoRequest2();
            inValue.Body = new clienteP2.procesoCompra.SolicitarPresupuestoRequest2Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor2)(this)).SolicitarPresupuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.OrdenarCompraResponse2 clienteP2.procesoCompra.proveedor2.OrdenarCompra(clienteP2.procesoCompra.OrdenarCompraRequest2 request) {
            return base.Channel.OrdenarCompra(request);
        }
        
        public bool OrdenarCompra(int nUnidades, string refProd) {
            clienteP2.procesoCompra.OrdenarCompraRequest2 inValue = new clienteP2.procesoCompra.OrdenarCompraRequest2();
            inValue.Body = new clienteP2.procesoCompra.OrdenarCompraRequest2Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.OrdenarCompraResponse2 retVal = ((clienteP2.procesoCompra.proveedor2)(this)).OrdenarCompra(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse2> clienteP2.procesoCompra.proveedor2.OrdenarCompraAsync(clienteP2.procesoCompra.OrdenarCompraRequest2 request) {
            return base.Channel.OrdenarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.OrdenarCompraResponse2> OrdenarCompraAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.OrdenarCompraRequest2 inValue = new clienteP2.procesoCompra.OrdenarCompraRequest2();
            inValue.Body = new clienteP2.procesoCompra.OrdenarCompraRequest2Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor2)(this)).OrdenarCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteP2.procesoCompra.ActualizarStockResponse3 clienteP2.procesoCompra.proveedor2.ActualizarStock(clienteP2.procesoCompra.ActualizarStockRequest3 request) {
            return base.Channel.ActualizarStock(request);
        }
        
        public bool ActualizarStock(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest3 inValue = new clienteP2.procesoCompra.ActualizarStockRequest3();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequest3Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            clienteP2.procesoCompra.ActualizarStockResponse3 retVal = ((clienteP2.procesoCompra.proveedor2)(this)).ActualizarStock(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse3> clienteP2.procesoCompra.proveedor2.ActualizarStockAsync(clienteP2.procesoCompra.ActualizarStockRequest3 request) {
            return base.Channel.ActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteP2.procesoCompra.ActualizarStockResponse3> ActualizarStockAsync(int nUnidades, string refProd) {
            clienteP2.procesoCompra.ActualizarStockRequest3 inValue = new clienteP2.procesoCompra.ActualizarStockRequest3();
            inValue.Body = new clienteP2.procesoCompra.ActualizarStockRequest3Body();
            inValue.Body.nUnidades = nUnidades;
            inValue.Body.refProd = refProd;
            return ((clienteP2.procesoCompra.proveedor2)(this)).ActualizarStockAsync(inValue);
        }
    }
}
