//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clienteMTIS1.ServiciosP1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/serviciosP1/", ConfigurationName="ServiciosP1.serviciosP1")]
    public interface serviciosP1 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/validarDNI", ReplyAction="*")]
        clienteMTIS1.ServiciosP1.validarDNIResponse validarDNI(clienteMTIS1.ServiciosP1.validarDNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/validarDNI", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.validarDNIResponse> validarDNIAsync(clienteMTIS1.ServiciosP1.validarDNIRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento iban del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/validarIBAN", ReplyAction="*")]
        clienteMTIS1.ServiciosP1.validarIBANResponse validarIBAN(clienteMTIS1.ServiciosP1.validarIBANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/validarIBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.validarIBANResponse> validarIBANAsync(clienteMTIS1.ServiciosP1.validarIBANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/consultaCP", ReplyAction="*")]
        clienteMTIS1.ServiciosP1.consultaCPResponse consultaCP(clienteMTIS1.ServiciosP1.consultaCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/consultaCP", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.consultaCPResponse> consultaCPAsync(clienteMTIS1.ServiciosP1.consultaCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/generarPresupuesto", ReplyAction="*")]
        clienteMTIS1.ServiciosP1.generarPresupuestoResponse generarPresupuesto(clienteMTIS1.ServiciosP1.generarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/generarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.generarPresupuestoResponse> generarPresupuestoAsync(clienteMTIS1.ServiciosP1.generarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/solicitarPresupuesto", ReplyAction="*")]
        clienteMTIS1.ServiciosP1.solicitarPresupuestoResponse solicitarPresupuesto(clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/serviciosP1/solicitarPresupuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.solicitarPresupuestoResponse> solicitarPresupuestoAsync(clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarDNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarDNI", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.validarDNIRequestBody Body;
        
        public validarDNIRequest() {
        }
        
        public validarDNIRequest(clienteMTIS1.ServiciosP1.validarDNIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarDNIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SoapKey;
        
        public validarDNIRequestBody() {
        }
        
        public validarDNIRequestBody(string dni, string SoapKey) {
            this.dni = dni;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarDNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarDNIResponse", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.validarDNIResponseBody Body;
        
        public validarDNIResponse() {
        }
        
        public validarDNIResponse(clienteMTIS1.ServiciosP1.validarDNIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarDNIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public validarDNIResponseBody() {
        }
        
        public validarDNIResponseBody(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBAN", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.validarIBANRequestBody Body;
        
        public validarIBANRequest() {
        }
        
        public validarIBANRequest(clienteMTIS1.ServiciosP1.validarIBANRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iban;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SoapKey;
        
        public validarIBANRequestBody() {
        }
        
        public validarIBANRequestBody(string iban, string SoapKey) {
            this.iban = iban;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBANResponse", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.validarIBANResponseBody Body;
        
        public validarIBANResponse() {
        }
        
        public validarIBANResponse(clienteMTIS1.ServiciosP1.validarIBANResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool valido;
        
        public validarIBANResponseBody() {
        }
        
        public validarIBANResponseBody(bool valido) {
            this.valido = valido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCP", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.consultaCPRequestBody Body;
        
        public consultaCPRequest() {
        }
        
        public consultaCPRequest(clienteMTIS1.ServiciosP1.consultaCPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaCPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SoapKey;
        
        public consultaCPRequestBody() {
        }
        
        public consultaCPRequestBody(string codp, string SoapKey) {
            this.codp = codp;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCPResponse", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.consultaCPResponseBody Body;
        
        public consultaCPResponse() {
        }
        
        public consultaCPResponse(clienteMTIS1.ServiciosP1.consultaCPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaCPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codPos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string poblacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string provincia;
        
        public consultaCPResponseBody() {
        }
        
        public consultaCPResponseBody(string codPos, string poblacion, string provincia) {
            this.codPos = codPos;
            this.poblacion = poblacion;
            this.provincia = provincia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarPresupuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarPresupuesto", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.generarPresupuestoRequestBody Body;
        
        public generarPresupuestoRequest() {
        }
        
        public generarPresupuestoRequest(clienteMTIS1.ServiciosP1.generarPresupuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarPresupuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechaPresupuesto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string referenciaProd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidadProd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SoapKey;
        
        public generarPresupuestoRequestBody() {
        }
        
        public generarPresupuestoRequestBody(string fechaPresupuesto, int idCliente, string referenciaProd, int cantidadProd, string SoapKey) {
            this.fechaPresupuesto = fechaPresupuesto;
            this.idCliente = idCliente;
            this.referenciaProd = referenciaProd;
            this.cantidadProd = cantidadProd;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarPresupuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarPresupuestoResponse", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.generarPresupuestoResponseBody Body;
        
        public generarPresupuestoResponse() {
        }
        
        public generarPresupuestoResponse(clienteMTIS1.ServiciosP1.generarPresupuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarPresupuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPresupuesto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool presupuestoGenerado;
        
        public generarPresupuestoResponseBody() {
        }
        
        public generarPresupuestoResponseBody(int idPresupuesto, bool presupuestoGenerado) {
            this.idPresupuesto = idPresupuesto;
            this.presupuestoGenerado = presupuestoGenerado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarPresupuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitarPresupuesto", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.solicitarPresupuestoRequestBody Body;
        
        public solicitarPresupuestoRequest() {
        }
        
        public solicitarPresupuestoRequest(clienteMTIS1.ServiciosP1.solicitarPresupuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class solicitarPresupuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string refPieza;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idProveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SoapKey;
        
        public solicitarPresupuestoRequestBody() {
        }
        
        public solicitarPresupuestoRequestBody(string refPieza, int idProveedor, string SoapKey) {
            this.refPieza = refPieza;
            this.idProveedor = idProveedor;
            this.SoapKey = SoapKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarPresupuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitarPresupuestoResponse", Namespace="http://www.example.org/serviciosP1/", Order=0)]
        public clienteMTIS1.ServiciosP1.solicitarPresupuestoResponseBody Body;
        
        public solicitarPresupuestoResponse() {
        }
        
        public solicitarPresupuestoResponse(clienteMTIS1.ServiciosP1.solicitarPresupuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class solicitarPresupuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precioPieza;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool dispPieza;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaDispPieza;
        
        public solicitarPresupuestoResponseBody() {
        }
        
        public solicitarPresupuestoResponseBody(float precioPieza, bool dispPieza, string fechaDispPieza) {
            this.precioPieza = precioPieza;
            this.dispPieza = dispPieza;
            this.fechaDispPieza = fechaDispPieza;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciosP1Channel : clienteMTIS1.ServiciosP1.serviciosP1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciosP1Client : System.ServiceModel.ClientBase<clienteMTIS1.ServiciosP1.serviciosP1>, clienteMTIS1.ServiciosP1.serviciosP1 {
        
        public serviciosP1Client() {
        }
        
        public serviciosP1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciosP1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosP1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosP1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteMTIS1.ServiciosP1.validarDNIResponse clienteMTIS1.ServiciosP1.serviciosP1.validarDNI(clienteMTIS1.ServiciosP1.validarDNIRequest request) {
            return base.Channel.validarDNI(request);
        }
        
        public bool validarDNI(string dni, string SoapKey) {
            clienteMTIS1.ServiciosP1.validarDNIRequest inValue = new clienteMTIS1.ServiciosP1.validarDNIRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.validarDNIRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.SoapKey = SoapKey;
            clienteMTIS1.ServiciosP1.validarDNIResponse retVal = ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).validarDNI(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.validarDNIResponse> clienteMTIS1.ServiciosP1.serviciosP1.validarDNIAsync(clienteMTIS1.ServiciosP1.validarDNIRequest request) {
            return base.Channel.validarDNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.validarDNIResponse> validarDNIAsync(string dni, string SoapKey) {
            clienteMTIS1.ServiciosP1.validarDNIRequest inValue = new clienteMTIS1.ServiciosP1.validarDNIRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.validarDNIRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.SoapKey = SoapKey;
            return ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).validarDNIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteMTIS1.ServiciosP1.validarIBANResponse clienteMTIS1.ServiciosP1.serviciosP1.validarIBAN(clienteMTIS1.ServiciosP1.validarIBANRequest request) {
            return base.Channel.validarIBAN(request);
        }
        
        public bool validarIBAN(string iban, string SoapKey) {
            clienteMTIS1.ServiciosP1.validarIBANRequest inValue = new clienteMTIS1.ServiciosP1.validarIBANRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.validarIBANRequestBody();
            inValue.Body.iban = iban;
            inValue.Body.SoapKey = SoapKey;
            clienteMTIS1.ServiciosP1.validarIBANResponse retVal = ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).validarIBAN(inValue);
            return retVal.Body.valido;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.validarIBANResponse> clienteMTIS1.ServiciosP1.serviciosP1.validarIBANAsync(clienteMTIS1.ServiciosP1.validarIBANRequest request) {
            return base.Channel.validarIBANAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.validarIBANResponse> validarIBANAsync(string iban, string SoapKey) {
            clienteMTIS1.ServiciosP1.validarIBANRequest inValue = new clienteMTIS1.ServiciosP1.validarIBANRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.validarIBANRequestBody();
            inValue.Body.iban = iban;
            inValue.Body.SoapKey = SoapKey;
            return ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).validarIBANAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteMTIS1.ServiciosP1.consultaCPResponse clienteMTIS1.ServiciosP1.serviciosP1.consultaCP(clienteMTIS1.ServiciosP1.consultaCPRequest request) {
            return base.Channel.consultaCP(request);
        }
        
        public string consultaCP(string codp, string SoapKey, out string poblacion, out string provincia) {
            clienteMTIS1.ServiciosP1.consultaCPRequest inValue = new clienteMTIS1.ServiciosP1.consultaCPRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.consultaCPRequestBody();
            inValue.Body.codp = codp;
            inValue.Body.SoapKey = SoapKey;
            clienteMTIS1.ServiciosP1.consultaCPResponse retVal = ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).consultaCP(inValue);
            poblacion = retVal.Body.poblacion;
            provincia = retVal.Body.provincia;
            return retVal.Body.codPos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.consultaCPResponse> clienteMTIS1.ServiciosP1.serviciosP1.consultaCPAsync(clienteMTIS1.ServiciosP1.consultaCPRequest request) {
            return base.Channel.consultaCPAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.consultaCPResponse> consultaCPAsync(string codp, string SoapKey) {
            clienteMTIS1.ServiciosP1.consultaCPRequest inValue = new clienteMTIS1.ServiciosP1.consultaCPRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.consultaCPRequestBody();
            inValue.Body.codp = codp;
            inValue.Body.SoapKey = SoapKey;
            return ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).consultaCPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteMTIS1.ServiciosP1.generarPresupuestoResponse clienteMTIS1.ServiciosP1.serviciosP1.generarPresupuesto(clienteMTIS1.ServiciosP1.generarPresupuestoRequest request) {
            return base.Channel.generarPresupuesto(request);
        }
        
        public int generarPresupuesto(string fechaPresupuesto, int idCliente, string referenciaProd, int cantidadProd, string SoapKey, out bool presupuestoGenerado) {
            clienteMTIS1.ServiciosP1.generarPresupuestoRequest inValue = new clienteMTIS1.ServiciosP1.generarPresupuestoRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.generarPresupuestoRequestBody();
            inValue.Body.fechaPresupuesto = fechaPresupuesto;
            inValue.Body.idCliente = idCliente;
            inValue.Body.referenciaProd = referenciaProd;
            inValue.Body.cantidadProd = cantidadProd;
            inValue.Body.SoapKey = SoapKey;
            clienteMTIS1.ServiciosP1.generarPresupuestoResponse retVal = ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).generarPresupuesto(inValue);
            presupuestoGenerado = retVal.Body.presupuestoGenerado;
            return retVal.Body.idPresupuesto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.generarPresupuestoResponse> clienteMTIS1.ServiciosP1.serviciosP1.generarPresupuestoAsync(clienteMTIS1.ServiciosP1.generarPresupuestoRequest request) {
            return base.Channel.generarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.generarPresupuestoResponse> generarPresupuestoAsync(string fechaPresupuesto, int idCliente, string referenciaProd, int cantidadProd, string SoapKey) {
            clienteMTIS1.ServiciosP1.generarPresupuestoRequest inValue = new clienteMTIS1.ServiciosP1.generarPresupuestoRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.generarPresupuestoRequestBody();
            inValue.Body.fechaPresupuesto = fechaPresupuesto;
            inValue.Body.idCliente = idCliente;
            inValue.Body.referenciaProd = referenciaProd;
            inValue.Body.cantidadProd = cantidadProd;
            inValue.Body.SoapKey = SoapKey;
            return ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).generarPresupuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clienteMTIS1.ServiciosP1.solicitarPresupuestoResponse clienteMTIS1.ServiciosP1.serviciosP1.solicitarPresupuesto(clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest request) {
            return base.Channel.solicitarPresupuesto(request);
        }
        
        public float solicitarPresupuesto(string refPieza, int idProveedor, string SoapKey, out bool dispPieza, out string fechaDispPieza) {
            clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest inValue = new clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.solicitarPresupuestoRequestBody();
            inValue.Body.refPieza = refPieza;
            inValue.Body.idProveedor = idProveedor;
            inValue.Body.SoapKey = SoapKey;
            clienteMTIS1.ServiciosP1.solicitarPresupuestoResponse retVal = ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).solicitarPresupuesto(inValue);
            dispPieza = retVal.Body.dispPieza;
            fechaDispPieza = retVal.Body.fechaDispPieza;
            return retVal.Body.precioPieza;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.solicitarPresupuestoResponse> clienteMTIS1.ServiciosP1.serviciosP1.solicitarPresupuestoAsync(clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest request) {
            return base.Channel.solicitarPresupuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<clienteMTIS1.ServiciosP1.solicitarPresupuestoResponse> solicitarPresupuestoAsync(string refPieza, int idProveedor, string SoapKey) {
            clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest inValue = new clienteMTIS1.ServiciosP1.solicitarPresupuestoRequest();
            inValue.Body = new clienteMTIS1.ServiciosP1.solicitarPresupuestoRequestBody();
            inValue.Body.refPieza = refPieza;
            inValue.Body.idProveedor = idProveedor;
            inValue.Body.SoapKey = SoapKey;
            return ((clienteMTIS1.ServiciosP1.serviciosP1)(this)).solicitarPresupuestoAsync(inValue);
        }
    }
}
